language: rust

script:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - cargo build --all --verbose
  - cargo test --all --verbose

rust:
  - stable

cache: cargo

branches:

  only:
    - master
