language: rust

script:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo test --verbose

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:

  allow_failures:
    - rust: nightly

  fast_finish: true

branches:

  only:
    - master
