[package]
name = "silica"
version = "0.0.1"
authors = ["Nick Kraus <nick@krauslabs.com>"]

[dependencies]
clap = "2.32.0"
lalrpop-util = "0.16.1"
regex = "1.0.6"

[build-dependencies]
lalrpop = "0.16.1"