[package]
name = "silica"
version = "0.0.1"
authors = ["Nick Kraus <nick@krauslabs.com>"]

[dependencies]
clap = "2.32.0"
codegen = { path = "src/libcodegen" }
syntax = { path = "src/libsyntax" }

[workspace]
members = [
	"./",
	"src/libcodegen",
	"src/libsyntax",
]