[package]
name = "silica"
version = "0.0.1"
authors = ["Nick Kraus <nick@krauslabs.com>"]

[dependencies]
clap = "2.32.0"
syntax = { path = "src/libsyntax" }
verilog = { path = "src/libverilog" }

[workspace]
members = [
	"./",
	"src/libsyntax",
	"src/libverilog",
]