[package]
name = "syntax"
version = "0.0.0"
authors = ["Nick Kraus <nick@krauslabs.com>"]

[lib]
name = "syntax"
path = "src/lib.rs"

[dependencies]
lalrpop-util = "0.16.1"
regex = "1.0.6"

[build-dependencies]
lalrpop = "0.16.1"
